name: Hello_world_Workflow
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: echo "Hello World"
        shell: bash
  wipe:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: ending
         run: echo "ending....CI/CD"
         shell: bash  

