name: create acomment on new issue
on:
  issues:
    types: [opened]
jobs:
  comment_with_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash